wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.11
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.9.7
    start_time: 1647989821
    t:
      1:
      - 1
      2:
      - 1
      4: 3.9.7
      5: 0.12.11
      8:
      - 5
amp:
  desc: null
  value: false
batch_size:
  desc: null
  value: 1
epochs:
  desc: null
  value: 5
img_scale:
  desc: null
  value: 0.5
learning_rate:
  desc: null
  value: 1.0e-05
save_checkpoint:
  desc: null
  value: true
val_percent:
  desc: null
  value: 0.1
